name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1.22'
          cache: false

      - name: Build Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o cpi.exe .

      - name: Build Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o cpi-linux .

      - uses: actions/upload-artifact@v6
        with:
          name: cpi-binaries
          path: |
            cpi.exe
            cpi-linux
